FORMAT: 1A
HOST: http://localhost:8020/

# ACTUM DIGITAL Be Test

Following API should proxy an integration between FE and Algolia search engine (https://www.algolia.com/). Please create a free account on algolia search and integrate it to this microservice. 

## Product collection [/product]

This collection is designed to work with single product

### Find a Product [GET/product/{objectID}]

+ Parameters
    + objectID: `Asd1g5-TTzHU45-SSH6` (string, required) - Object ID of a record which should be deleted

+ Response 200 (application/json)

    + Body

            {
                "objectID": "Asd1g5-TTzHU45-SSH6",
                "name": "Sausage",
                "description": "A sausage is a type of meat product usually made from ground meat, often pork, beef, or poultry, along with salt, spices and other flavourings. Other ingredients such as grains or breadcrumbs may be included as fillers or extenders.",
                "type": "meal",
            }
    
    + Attributes
        + objectID (string) - Unique id of a record
        + name (string) - Name of a product
        + description (string) - Description of a product
        + type (enum[string]) Type of a product
            + Members
                + `meal`
                + `cloth`
                + `other stuff`


### Index a Product [POST]

+ Request (application/json)

    + Attributes
        + objectID (string) - Unique id of a record
        + name (string) - Name of a product
        + description (string) - Description of a product
        + type (enum[string]) Type of a product
            + Members
                + `meal`
                + `cloth`
                + `other stuff`

    + Headers

            Authorization: Bearer JWT

    + Body

            {
                "objectID": "Asd1g5-TTzHU45-SSH6",
                "name": "Sausage",
                "description": "A sausage is a type of meat product usually made from ground meat, often pork, beef, or poultry, along with salt, spices and other flavourings. Other ingredients such as grains or breadcrumbs may be included as fillers or extenders.",
                "type": "meal",
            }

+ Response 201 (application/json)

    + Body

            {
                "status": "OK",
                "message": "success",
                "code": "200",
            }

### Delete a Product [DELETE/product/{objectID}]

+ Parameters
    + objectID: `Asd1g5-TTzHU45-SSH6` (string, required) - Object ID of a record which should be deleted

+ Request (application/json)

    + Headers

            Authorization: Bearer JWT
  

+ Response 201 (application/json)

    + Body

            {
                "status": "OK",
                "message": "success",
                "code": "200",
            }

## Products collection [/products]
This collection is designed to commit "bulk" operations above products

### Find products [GET/{?offset, ?limit}]

+ Parameters
    + offset (number, optional) - How many records should be skipped
        + Default: 0
    + limit (number, optional) - How many records should be retrieved
        + Default: 100

+ Request

    + Body

            {
                "objectID": ["Asd1g5-TTzHU45-SSH6", "Asd1g5-TTzHU45-SSH6"],
            }
    
    + Attributes
        + objectID (array[string], optional) - List of unique ids of products (if empty, all products are shown)

+ Response 200 (application/json)

    + Body

            {
                "objectID": "Asd1g5-TTzHU45-SSH6",
                "name": "Sausage",
                "description": "A sausage is a type of meat product usually made from ground meat, often pork, beef, or poultry, along with salt, spices and other flavourings. Other ingredients such as grains or breadcrumbs may be included as fillers or extenders.",
                "type": "meal",
            }
    
    + Attributes
        + objectID (string) - Unique id of a record
        + name (string) - Name of a product
        + description (string) - Description of a product
        + type (enum[string]) Type of a product
            + Members
                + `meal`
                + `cloth`
                + `other stuff`

### Index products [POST]

+ Request (application/json)

    + Attributes
        + Items (array [IndexingItem])

    + Headers

            Authorization: Bearer JWT

    + Body

            [
                {
                    "objectID": "Asd1g5-TTzHU45-SSH6",
                    "name": "Sausage",
                    "description": "A sausage is a type of meat product usually made from ground meat, often pork, beef, or poultry, along with salt, spices and other flavourings. Other ingredients such as grains or breadcrumbs may be included as fillers or extenders.",
                    "type": "meal",
                },
                {
                    "objectID": "Asd1g5-TTzHU45-SSH6",
                    "name": "Sausage",
                    "description": "A sausage is a type of meat product usually made from ground meat, often pork, beef, or poultry, along with salt, spices and other flavourings. Other ingredients such as grains or breadcrumbs may be included as fillers or extenders.",
                    "type": "meal",
                },
            ]

+ Response 201 (application/json)

    + Body

            {
                "status": "OK",
                "message": "success",
                "code": "200",
            }

### Delete a Product [DELETE]

+ Request (application/json)

    + Headers

            Authorization: Bearer JWT

    + Body

            {
                "objectIDs": ["Asd1g5-TTzHU45-SSH6", "Asd1g5-TTzHU45-SSH6"],
            }
    
    + Attributes
        + objectIDs (array [ObjectID])

+ Response 201 (application/json)

    + Body

            {
                "status": "OK",
                "message": "success",
                "code": "200",
            }

# Data structures
## IndexingItem
+ objectID (string) - Unique id of a record
+ name (string) - Name of a product
+ description (string) - Description of a product
+ type (enum[string]) Type of a product
    + Members
        + `meal`
        + `cloth`
        + `other stuff`

## ObjectID (string) - Unique id of a record